# Generated by Django 5.1.6 on 2025-02-27 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DogReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('condition', models.CharField(choices=[('Healthy', 'Healthy'), ('Injured', 'Injured'), ('Lost', 'Lost')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='dog_reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
