# Generated by Django 4.2.19 on 2025-03-04 10:46

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogreport',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dogreport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.unique_filename),
        ),
    ]
