# Generated by Django 5.1.6 on 2025-03-01 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_dogreport_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccinated', models.BooleanField(default=False)),
                ('rescued', models.BooleanField(default=False)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dog_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='api.dogreport')),
            ],
        ),
    ]
